### ISSUE TITLE
Push environments to ghcr.io and docker.io

### ISSUE THREAD

**Issue by bryanhonof** [flox/floxenvs#60]
We'd like for these example environments to be pushed to the ghcr.io and docker.io container registries. This will require us to first turn these Flox environments into containers with something like `flox containerize`.

## Acceptance Criteria

- [x] There _must_ be a workflow that automatically turns these example environments into containers
- [x] The resulting containers _must_ be pushed to ghcr.io
- [ ] The resulting containers _may_ be pushed to docker.io

**Comment by tomberek** [comment]
https://hub.docker.com/orgs/floxdev

**Comment by bryanhonof** [comment]
It seems that `flox containerize` doesn't start services automatically when starting a container. So, we can get the automation in place, but the containers themselves won't be as nice to use until we address the aforementioned issue.

**Comment by tomberek** [comment]
Thanks... then we need to see what possibilities there are. Can we install flox itself into the envs... start watchdog/process-compose that way?

**Comment by garbas** [comment]
@stahnma I think we should skip pushing to docker.io since we are also not pushing flox docker image there.
